---
- name: Install the latest packages for Apache
  dnf: name={{ item }} state=latest
  with_items:
    - httpd
    # Dependencies for firewalld role
    - firewalld
    - python-firewall
    - cockpit
  notify:
    - restart apache
    - restart firewall

- name: Start Apache and Firewalld
  shell: service {{ item }} restart
  with_items:
  - httpd
  - firewalld

# https://fedoraproject.org/wiki/Apache_HTTP_Server#Opening_firewall_ports
- name: Open firewall ports for the webserver
  firewalld: service=http permanent=true state=enabled immediate=true