---
- name: Install the latest version of apache2
  dnf: name=httpd state=latest

- name: Enable required Apache modules
  apache2_module: name={{ item }} state=present
  with_items:
    - cgi
    - rewrite
  notify:
    - restart apache

# TODO: firewall?