---
- name: Configure Apache as required by Koha
  copy: src=../files/koha-httpd.conf dest=/etc/httpd/conf.d/koha.conf

- name: Create a user for Koha
  user: name=koha comment="Koha server" group=apache

- name: Make perl find the Koha modules
  file: src=/usr/share/koha/lib/C4 dest=/usr/share/perl5/vendor_perl/C4 state=link force=yes
  file: src=/usr/share/koha/lib/Koha dest=/usr/share/perl5/vendor_perl/Koha state=link force=yes
  file: src=/usr/share/koha/lib/OpenILS dest=/usr/share/perl5/vendor_perl/OpenILS state=link force=yes
  file: src=/usr/share/koha/lib/Koha.pm dest=/usr/share/perl5/vendor_perl/Koha.pm state=link force=yes
  notify: restart apache

#- name: Add cronjobs for Koha
#  copy: src=../files/koha-cron dest=/etc/cron.d/koha

# Defaults for firewall, SELinux, Zebra and PazPar2 seem to work.
# TODO: Define ServerName in Apache configuration