---
- name: Configure Apache as required by Koha
  copy: src=../files/koha.conf dest=/etc/httpd/conf.d/koha.conf

# TODO: other firewall rules http://wiki.koha-community.org/wiki/Koha_3.10_on_Centos_6.3_x86_64_en#.C4.B0ptables_rules
# TODO: Configure the virtualhost https://www.digitalocean.com/community/tutorials/how-to-configure-apache-using-ansible-on-ubuntu-14-04
# TODO: Configure SELinux http://www.serverlab.ca/tutorials/linux/web-servers-linux/configuring-selinux-policies-for-apache-web-servers/