---

# The following tasks are based on the instructions found at the following URLs:
# http://wiki.koha-community.org/wiki/Koha_3.10_on_Centos_6.3_x86_64_en
# http://bugs.koha-community.org/bugzilla3/buglist.cgi?bug_id=12549,15405

- name: Install main Koha prerequisites
  dnf: name={{ item }} state=latest
  with_items:
    - yaz
    - libidzebra
    - libidzebra-modules
    - libidzebra-devel
    - idzebra
    - memcached
    # TODO: Check what of the following is really required.
    - gcc
    - patch
    - tcl
    - libicu-devel
    - make
    - openssh-clients
    - vim
    - wget
    - setools
    - policycoreutils-python
    - cyrus-sasl-plain

- name: Install additional perl prerequisites
  dnf: name={{item}} state=latest
  with_items:
    - at # https://lists.katipo.co.nz/public/koha/2011-June/029684.html
    - fribidi-devel # Configure failed for Text-Bidi-2.11. It seems that fribidi is missing.
    - libyaz-devel # Required to build Net::Z3950::ZOOM from CPAN
    - libuuid-devel # Configure failed for UUID-0.24. Can't link/include C library 'uuid', aborting.
    - GraphicsMagick-perl
    - perl-Algorithm-CheckDigits
    - perl-App-cpanminus
    - perl-Authen-CAS-Client
    - perl-Biblio-EndnoteStyle
    - perl-Cache-Memcached
    - perl-CGI
    - perl-CGI-Session
    - perl-CPAN
    - perl-CPAN-Meta-YAML
    - perl-Class-Factory-Util
    - perl-DBD-Mock
    - perl-DBD-SQLite2
    - perl-DBIx-Class-Schema-Loader
    - perl-Data-ICal
    - perl-Date-Calc
    - perl-Date-Manip
    - perl-DateTime
    - perl-DateTime-Event-ICal
    - perl-DateTime-Format-ICal
    - perl-DateTime-Format-MySQL
    - perl-DateTime-Set
    - perl-DateTime-TimeZone
    - perl-Email-Date
    - perl-Email-Valid
    - perl-Exception-Class
    - perl-Font-TTF
    - perl-HTML-Scrubber
    - perl-HTTP-OAI
    - perl-JSON
    - perl-Library-CallNumber-LC
    - perl-Lingua-Stem
    - perl-Lingua-Stem-Snowball
    - perl-Locale-Currency-Format
    - perl-Locale-Maketext-Lexicon
    - perl-Locale-PO
    - perl-Log-Log4perl
    - perl-MARC-Charset
    - perl-MARC-Record
    - perl-MIME-Lite
    - perl-Mail-Sendmail
    - perl-Modern-Perl
    - perl-Moose
    - perl-Net-Server
    - perl-Number-Format
    - perl-PDF-API2
    - perl-PDF-Reuse
    - perl-Plack-Middleware-ReverseProxy
    - perl-String-Random
    - perl-Test-MockModule
    - perl-Test-YAML-Valid
    - perl-Text-CSV
    - perl-Text-CSV_XS
    - perl-Text-Iconv
    - perl-Text-PDF
    - perl-Time-Progress
    - perl-UNIVERSAL-can
    - perl-UNIVERSAL-require
    - perl-Unix-Syslog
    - perl-XML-Dumper
    - perl-XML-LibXML
    # TODO: Warning: XML::LibXML compiled against libxml2 20903, but runtime libxml2 is older 20902
    - perl-XML-LibXSLT
    - perl-XML-RSS
    - perl-XML-SAX-Writer
    - perl-XML-Simple
    - perl-YAML

- name: Install missing perl dependencies from CPAN
  cpanm: name={{ item }}
  with_items:
    - CGI::Session::Serialize::yaml
    - Crypt::Eksblowfish::Bcrypt
    - GD::Barcode::UPCE
    - HTML::FormatText
    - Locale::Language
    - MARC::Crosswalk::DublinCore
    - MARC::File::XML
    - Net::Z3950::ZOOM
    - open # Module 'open' is not installed ! Bailing out the installation for Text-Bidi-2.11.
    - OpenOffice::OODoc
    # TODO: duplicates the package above?
    - CHROMATIC/PDF-API2-Simple-1.1.5.tar.gz # https://rt.cpan.org/Public/Bug/Display.html?id=28125#txn-1303659
    - PDF::Reuse::Barcode
    - PDF::Table
    - Schedule::At
    - Template::Plugin::HtmlToText
    - Template::Plugin::JSON::Escape
    # - Text::Bidi # TODO: Still fails
    - Text::CSV::Encoded
    - Text::Unaccent
    - UUID

# TODO: install Koha

- name: Configure Apache
  include: apache.yml

- name: Configure webserver for Koha
  include: koha-webserver.yml

- name: Install MySQL server locally
  include: mysql.yml

