---

# The following tasks are based on the instructions found at the following URLs:
# http://wiki.koha-community.org/wiki/Koha_3.10_on_Centos_6.3_x86_64_en
# http://bugs.koha-community.org/bugzilla3/buglist.cgi?bug_id=12549,15405

- name: Install Koha dependencies
  include: koha-dependencies-fedora.yml

# TODO: install Koha

- name: Configure Apache
  include: apache.yml

- name: Configure webserver for Koha
  include: koha-webserver.yml

- name: Install MySQL server locally
  include: mysql.yml

