---

# The following tasks are based on the instructions found at the following URLs:
# http://wiki.koha-community.org/wiki/Koha_3.10_on_Centos_6.3_x86_64_en
# http://bugs.koha-community.org/bugzilla3/buglist.cgi?bug_id=12549,15405

- name: Install main Koha prerequisites
  dnf: name={{ item }} state=latest
  with_items:
    - yaz
    - libidzebra
    - libidzebra-modules
    - libidzebra-devel
    - idzebra
    # TODO: Check what of the following is really required.
    - gcc
    - patch
    - tcl
    - libicu-devel
    - make
    - openssh-clients
    - vim
    - wget
    - setools
    - policycoreutils-python
    - cyrus-sasl-plain

# TODO: What to do with SELinux?

- name: Install additional perl prerequisites
  dnf: name={{item}} state=latest
  with_items:
    - GraphicsMagick-perl
    - perl-Algorithm-CheckDigits
    - perl-Authen-CAS-Client
    - perl-Biblio-EndnoteStyle
    - perl-CGI
    - perl-CGI-Session
    - perl-CPAN
    - perl-CPAN-Meta-YAML
    - perl-Class-Factory-Util
    - perl-DBD-Mock
    - perl-DBD-SQLite2
    - perl-DBIx-Class-Schema-Loader
    - perl-Data-ICal
    - perl-Date-Calc
    - perl-Date-Manip
    - perl-DateTime
    - perl-DateTime-Event-ICal
    - perl-DateTime-Format-ICal
    - perl-DateTime-Format-MySQL
    - perl-DateTime-Set
    - perl-DateTime-TimeZone
    - perl-Email-Date
    - perl-Email-Valid
    - perl-Exception-Class
    - perl-Font-TTF
    - perl-HTML-Scrubber
    - perl-HTTP-OAI
    - perl-JSON
    - perl-Library-CallNumber-LC
    - perl-Lingua-Stem
    - perl-Lingua-Stem-Snowball
    - perl-Locale-Currency-Format
    - perl-Locale-Maketext-Lexicon
    - perl-Locale-PO
    - perl-Log-Log4perl
    - perl-MARC-Charset
    - perl-MARC-Record
    - perl-MIME-Lite
    - perl-Mail-Sendmail
    - perl-Modern-Perl
    - perl-Moose
    - perl-Net-Server
    - perl-Number-Format
    - perl-PDF-API2
    - perl-PDF-Reuse
    - perl-Plack-Middleware-ReverseProxy
    - perl-String-Random
    - perl-Test-MockModule
    - perl-Test-YAML-Valid
    - perl-Text-CSV
    - perl-Text-CSV_XS
    - perl-Text-Iconv
    - perl-Text-PDF
    - perl-Time-Progress
    - perl-UNIVERSAL-can
    - perl-UNIVERSAL-require
    - perl-Unix-Syslog
    - perl-XML-Dumper
    - perl-XML-LibXML
    - perl-XML-LibXSLT
    - perl-XML-RSS
    - perl-XML-SAX-Writer
    - perl-XML-Simple
    - perl-YAML

# TODO: install Koha

- name: Install MySQL Server locally
  include: mysql.yml

- name: Configure Apache
  include: apache.yml

